$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: CssTemplateConfiguration
    derivedFromCkTypeId: ${System}/Configuration
    isFinal: true
    attributes:
      - id: ${this}/CssStyle
        name: CssStyle
