<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <RootNamespace>ArtifactStorage.Tests</RootNamespace>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FakeItEasy" Version="9.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.10.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="Testcontainers.Azurite" Version="4.14.0" />
        <PackageReference Include="Testcontainers.Minio" Version="4.14.0" />
        <PackageReference Include="xunit.v3.mtp-off" Version="4.0.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ArtifactStorage\ArtifactStorage.csproj" />
    </ItemGroup>

</Project>
