using System.Collections.Generic;

using Meshmakers.Octo.Services.Observability;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;

using Xunit;

namespace Observability.Tests;

/// <summary>
///     Pins the OpenTelemetry resource identity produced by <c>AddObservability()</c>.
/// </summary>
/// <remarks>
///     <para>
///         AB#5478 §2.1. Three producers attach a <c>service.name</c> to the signals of one pod and
///         they disagreed: the in-process SDK used the entry assembly name, the injected
///         auto-instrumentation used <c>OTEL_SERVICE_NAME</c>, and the log collector used a pod
///         label. These tests cover the half this process controls — that the deployment's
///         <c>OTEL_SERVICE_NAME</c> wins over the assembly name, and that the fallback still works
///         where the variable is absent.
///     </para>
///     <para>
///         The precedence being pinned here is not documented by OpenTelemetry; it falls out of
///         <c>Resource.Merge</c> (later detector wins) and the order in which <c>ConfigureResource</c>
///         appends to <c>ResourceBuilder.CreateDefault()</c>. That is exactly why it is worth a test:
///         an SDK upgrade could flip it, and the symptom in production would be a silent identity
///         split rather than a failure.
///     </para>
/// </remarks>
public class ServiceIdentityTests
{
    private const string ServiceNameKey = "OTEL_SERVICE_NAME";
    private const string ServiceNameAttribute = "service.name";
    private const string ServiceInstanceIdAttribute = "service.instance.id";

    [Fact]
    public void OtelServiceName_WhenSet_WinsOverTheEntryAssemblyName()
    {
        var resource = BuildResource(otelServiceName: "octo-mesh-identity-services");

        Assert.Equal("octo-mesh-identity-services", GetAttribute(resource, ServiceNameAttribute));
    }

    [Fact]
    public void OtelServiceName_WhenAbsent_FallsBackToTheApplicationName()
    {
        var builder = Host.CreateApplicationBuilder();
        var expected = builder.Environment.ApplicationName;

        var resource = BuildResource(otelServiceName: null, builder);

        Assert.Equal(expected, GetAttribute(resource, ServiceNameAttribute));
    }

    /// <summary>
    ///     An empty value counts as "set" to IConfiguration, and AddService throws on an empty
    ///     serviceName. A chart that renders the variable without a value must not take the process
    ///     down at startup.
    /// </summary>
    [Fact]
    public void OtelServiceName_WhenEmpty_FallsBackInsteadOfThrowing()
    {
        var builder = Host.CreateApplicationBuilder();
        var expected = builder.Environment.ApplicationName;

        var resource = BuildResource(otelServiceName: string.Empty, builder);

        Assert.Equal(expected, GetAttribute(resource, ServiceNameAttribute));
    }

    /// <summary>
    ///     service.instance.id is auto-generated by AddService and is the only source for it in the
    ///     estate — the Dash0 operator sets it on no signal. Dropping the AddService call would have
    ///     been the tidier way to let OTEL_SERVICE_NAME win, and would have silently lost this.
    /// </summary>
    [Fact]
    public void ServiceInstanceId_IsStillGenerated_WhenOtelServiceNameWins()
    {
        var resource = BuildResource(otelServiceName: "octo-mesh-identity-services");

        var instanceId = GetAttribute(resource, ServiceInstanceIdAttribute);

        Assert.False(string.IsNullOrWhiteSpace(instanceId));
    }

    private static Resource BuildResource(string? otelServiceName, HostApplicationBuilder? existing = null)
    {
        var builder = existing ?? Host.CreateApplicationBuilder();

        if (otelServiceName is not null)
        {
            builder.Configuration.AddInMemoryCollection(
                new Dictionary<string, string?> { [ServiceNameKey] = otelServiceName });
        }

        builder.AddObservability();

        // Observe the resource as AddObservability composed it: this callback is registered after
        // the one inside AddObservability, so by the time it runs the builder already carries the
        // AddService result, and Build() merges it exactly as the provider would.
        Resource? captured = null;
        builder.Services.ConfigureOpenTelemetryMeterProvider(
            meterProvider => meterProvider.ConfigureResource(resource => captured = resource.Build()));

        using var host = builder.Build();

        // Resolving the provider is what forces the resource to be built.
        _ = host.Services.GetRequiredService<MeterProvider>();

        Assert.NotNull(captured);
        return captured;
    }

    private static string? GetAttribute(Resource resource, string key)
    {
        foreach (var attribute in resource.Attributes)
        {
            if (attribute.Key == key)
            {
                return attribute.Value as string;
            }
        }

        return null;
    }
}
